### ISSUE TITLE
Feature request: Include transactional email bounces

### ISSUE THREAD

**Issue by laryn** [proexchange/com.pesc.sparkpost#10]
This is a feature request to include transactional emails (event registration receipts, donation receipts, "Email contact" actions...) in the bounce responses, perhaps using the webhook feature of SparkPost?

**Comment by joseltorres** [comment]
This is something I want to add to a later release. Thanks for the input.

**Comment by JoeMurray** [comment]
Any sense of when you might address this feature request? I'd like to move some installations away from Mandrill for transactional emails. BTW, was this extension developed for Veda?

**Comment by mark-rodgers** [comment]
@JoeMurray Should be a pretty simple fix. Don't quote me on this but it can probably be fixed within this week. Also no this was not developedfor Veda. Our company also used Mandrill and after the recent changes decided to switch to SparkPost. We saw the need for a SparkPost CiviCRM extension and decided to create something and share it for others in the same situation as us.

**Comment by joseltorres** [comment]
@JoeMurray @laryn 
Transactional email bounce processing has been added to 1.3
https://github.com/proexchange/com.pesc.sparkpost/releases/tag/1.3
