### ISSUE TITLE
Difficulty getting SparkPost extension operating correctly in CiviCRM on WordPress

### ISSUE THREAD

**Issue by caniwigirl** [proexchange/com.pesc.sparkpost#13]
I have followed the instructions under SETUP STEPS, but as sone as I install and enable the extension (v1.3) in my WordPress site running CiviCRM 4.6.12, it no longer sends email through CiviMail, however it still send transactional email from WordPress.

When enabled, the scheduled job for SparkPost Action: Fetchbounces completes with a result of: Success (a:0:{})

CiviMail email send fine when the extension is NOT enabled.

Any suggestions?

Cheers

**Comment by joseltorres** [comment]
Can you successfully get setup and send through SparkPost (Setup Steps 1-4) without the extension enabled?

**Comment by jwachuta** [comment]
Using version 1.3 of this extension in CiviCRM 4.7.4 and WordPress 4.4.2 gives me the following error when Cron runs:

> PHP Fatal error:  Call to undefined function sparkpost_queue() in wp-content/plugins/files/civicrm/custom_ext/com.pesc.sparkpost/sparkpost.php on line 282

The error only began after a mailing was scheduled in CiviMail, and it causes all scheduled jobs to fail including "Send Scheduled Mailings." Reverting to version 1.2 of the extension appears to make the error go away and allows mailing to resume.

**Comment by joseltorres** [comment]
Thanks for the details, I will look into it soon.

**Comment by joseltorres** [comment]
we've identified the issue and will release a fix soon. Thanks for letting us know.

**Comment by joseltorres** [comment]
fixed https://github.com/proexchange/com.pesc.sparkpost/releases/tag/1.3.1
