### ISSUE TITLE
Please expand on setup documentation

### ISSUE THREAD

**Issue by tabletguy** [proexchange/com.pesc.sparkpost#14]
Step 3 says "Create API key" but Sparkpost onboarding says "Send with SMTP or Send with Rest"

And, after verifying email address, it uses different terminology for setting up "SPF Text Record" and "DKIM Record".

Could you clarify the steps by incorporating these two screen shots (or similar).

**Do I need to do BOTH sections?** (Send with ???) and setting up both (or just one of) the SPF and DKIM?  (Pretty sure I need to do both SPF and DKIM but I'm not seeing it in your documentation).

Sorry if this seems to much like "please hold my hand". I hope it's not a trivial question. Just let me know if it is.

![sparkpost_onboarding_getting_started](https://cloud.githubusercontent.com/assets/2747867/14433208/ff603c2c-ffd2-11e5-9b30-98fae7629464.png)

![spf_or_dkim_or_both](https://cloud.githubusercontent.com/assets/2747867/14433283/569630aa-ffd3-11e5-90bb-39bff29c5192.png)

Thanks in advance.

**Comment by mark-rodgers** [comment]
The extension sends out of SMTP, not the Rest API. You do need to generate an API key in your SparkPost account though which will be used as your SMTP password.

This should be referred to the SparkPost documentation ( https://support.sparkpost.com ) but I will briefly give you a walkthrough.

**1. Setup sending domain:**
        SparkPost requires you verify your domain using at least 1 out of the 3 methods. Although for better deliverability I would highly suggest also setting up SPF and DKIM.

**2. Generate API key:**
        Navigate to Account -> API Keys in the SparkPost web ui. Click the Create API Key button and select appropriate permissions. Make sure to save this API key somewhere as SparkPost will only show you it once before hiding it. You will need to use this API key as the password when setting up SMTP in CiviCRM.

**3. CiviCRM SMTP Setup**
        Setup SMTP sending in CiviCRM under **System Settings => Outbound Email**.
- Select mailer: SMTP
- SMTP server: smtp.sparkpostmail.com
- Port: (587 OR 2525)
- Authentication: Yes
- Username: SMTP_Injection
- Password: [API_KEY]

After following these first 3 steps I listed above you will want to resume setup procedures starting at Step 5 in the README.md file: https://github.com/proexchange/com.pesc.sparkpost/blob/master/README.md

**Comment by tabletguy** [comment]
Thanks much. I'd suggest adding the first sentence, the reference to sparkpost's article (which I didn't find, so thanks double) to the "**readme**"

I do think your points 1 and 2 would make a good expansion on the existing readme as well. Most people won't find the expanded explanation here...

Again, thanks!
