### ISSUE TITLE
campaign_id is limited to 64 bytes

### ISSUE THREAD

**Issue by herbdool** [proexchange/com.pesc.sparkpost#15]
A client got this warning when they added a mailing name that SparkPost can't handle as a campaign_id. Might be a good idea to catch this before it gets to SparkPost and throws back a cryptic response. Should you also force the campain_id to be ASCII as well since UTF-8 could easily fill up the allowed bytes?

Thanks guys! This extension is working well and a lot cheaper than trying to stay with Mandrill.

![civi_error_message_apr_12_2016](https://cloud.githubusercontent.com/assets/1071483/14467456/6c2ec9be-00a9-11e6-9f4a-a64767a3835e.png)

**Comment by joseltorres** [comment]
Thanks for letting us know. We'll definitely add this to the next release.

**Comment by mark-rodgers** [comment]
Fixed this bug in the latest commit 6e9a295e7b01523a3b7cba1eaceb3980ca16c92e. I converted the mailing name to UTF-8 and truncated it to a max of 64bytes before sending it to SparkPost.
