### ISSUE TITLE
Reconciling Civi and Sparkpost reports

### ISSUE THREAD

**Issue by davyrhys** [proexchange/com.pesc.sparkpost#18]
My campaign last night has differing results in Sparkpost and Civi. I have just run the cron.

Metric                     Sparkpost | Civi
Targeted                  450   |   437 (intended recipients)
Accepted                 417   |   269 (successful)  
Bounced                  33     |   168
Rendered                340   |   318
Unique rendered     99     |   98
Clicks                      6       |   1

The Civi bounce report shows that most are because of greylisting (see attached report).
[IRSSA BDay mailing report Report_Bounces.xlsx](https://github.com/proexchange/com.pesc.sparkpost/files/231450/IRSSA.BDay.mailing.report.Report_Bounces.xlsx)

**Comment by joseltorres** [comment]
So part of the issue to begin with is that the terms used in CiviCRM and SparkPots are not exactly the same. For instance, a message is delayed in SparkPost because the MX servers could not be reached. A "Delay" message event would occur, which is like a soft bounce. A bounce will get marked in civi. SparkPost will still attempt to send it later. So it may be 1 hour later or 1 day later, but it may still get delivered when the recipients mail server is no longer having issues. It may be useful to review these docs

https://support.sparkpost.com/customer/en/portal/articles/1929969-sparkpost-deliverability-metrics?b_id=7411

https://support.sparkpost.com/customer/en/portal/articles/2241721-how-are-messages-retried-in-sparkpost-and-sparkpost-elite-?b_id=7411

**Comment by davyrhys** [comment]
Hi Jose

Thanks for the links, they were helpful in understanding the situation.

Unfortunately the challenge remains that Civi is showing the initial
bounces and poor delivery rate, even though the actual deliveries - as
reported by Sparkpost - are dramatically better because the delayed mails
are later delivered. In my case it is a day after the campaign went out and
at least 8 hours since Sparkpost started showing that only 33 emails
bounced, and Civi is still showing 168 bounces :-(

Is it possible to fix this? Possibly by not fetching or ignoring the
'delayed' reports, or by updating the Civi records when the mails are
successfully delivered?
Or is this something we have to live with? Which means we can't rely on the
Civi mailing reports at all.

Kind regards
Davy

...

_DAVY IVINS_
T:  011 656 0946
C:  084 207 8148
davy.ivins@gmail.com

**Comment by joseltorres** [comment]
Yes you can change what is considered a bounce using the 'events' parameter in the scheduled job. We will also consider updating bounce/delivery on successful deliveries. 

https://github.com/proexchange/com.pesc.sparkpost/blob/master/README.md#scheduled-job-parameters-notes

**Comment by joseltorres** [comment]
A quick note... if you remove delay from the list of events considered bounces, you may have some false successful deliveries until the maximum number of delays occur in which case you'll get a bounce, but it may be up to 24 hours later.

**Comment by tabletguy** [comment]
Isn't there a larger issue, with CiviCRM eventually putting bounced email addresses on hold? I don't recall how many bounces are needed for that, or how it handles soft versus hard bounce.

**Comment by joseltorres** [comment]
We only count the first delay as a soft bounce. We ignore any subsequent delays. So if SparkPost attempts 4 times and delays or bounces every time, we only count one. This would be similar to how an email sent with the php mail() function would work. We let CiviCRM handle the type of bounce and how many of them place emails on hold. We pass the exact bounce/delay message to CiviCRM and it reads it, categorizes it, and marks email on hold if appropriate. 

see this for a little more info: https://wiki.civicrm.org/confluence/display/CRMDOC/Bounce+Handling#BounceHandling-WhyisaContactputon"hold"?

**Comment by davyrhys** [comment]
Hi Jose

Just to confirm - to prevent the extension retrieving the 'delay' bounces I should add the event parameter to the Civi scheduled job but remove the 'delay' event i.e.  "event=bounce,policy_rejection,out_of_band,spam_complaint". 

(I understand that this "may have some false successful deliveries until the maximum number of delays occur in which case you'll get a bounce, but it may be up to 24 hours later.")

**Comment by joseltorres** [comment]
Correct

-------- Original message --------
