### ISSUE TITLE
Undefined variable 'froms'

### ISSUE THREAD

**Issue by tabletguy** [proexchange/com.pesc.sparkpost#21]
I'm seeing this error in the CiviCRM error log.
Joomla 4.6.15, php 5.6

[05-May-2016 10:00:04 America/Chicago] PHP Notice:  Undefined variable: froms in /home/ahymsinc/public_html/main/media/civicrm/custom_ext/com.pesc.sparkpost/sparkpost.php on line 414

Let me know if you need more details.

**Comment by joseltorres** [comment]
CiviCRM version?
Do you have 1 or more enabled from email addresses in _Administer -> CiviMail -> From Email Addresses_ ?

**Comment by joseltorres** [comment]
NVM... figured it out, will fix and commit soon.

**Comment by joseltorres** [comment]
fixed. https://github.com/proexchange/com.pesc.sparkpost/commit/eeeabd42381ee2076f2574a4106391c0f7da8c8d

**Comment by tabletguy** [comment]
Sorry to bother you. I've just checked my error_log file and am still getting the undefined froms variable on line 414

I have 1.3.4 installed under extensions (Joomla 3.6.5, CiviCRM 4.7.15) and I was wondering if your fix (May 26, 2016) was ever pushed to a new release?

Should I just try and edit the file directly on the server?

**Comment by tabletguy** [comment]
I see in the info.xml that current version should be 1.3.5

So, I guess my question changes to why the update has never shown up in CiviCRM extensions manager?

Do I have to manually install it?

**Comment by joseltorres** [comment]
no release with the fix has been made yet. you can manually edit or just download the master branch
