### ISSUE TITLE
Send mailing fails with PHP 5.6 works with 5.5

### ISSUE THREAD

**Issue by tabletguy** [proexchange/com.pesc.sparkpost#22]
We upgraded the site to CiviCRM 4.7.7 a few weeks ago, but this is the first mailing since then. I'm only guessing that it's because of the 4.7.7 (from 4.6.latest).

The mailing started correctly, but seems to send one email per 10 minute (cron job) cycle. 

That one email returns an error (below). Scheduled Job log file only says mailing is started, it never lists as finished. 

**authentication failure [SMTP: STARTTLS failed (code: 220, response: 2.0.0 continue)]**

Joomla 3.5.1
PHP 5.6

**Comment by tabletguy** [comment]
I found a comment on StackExchange about downgrading from PHP 5.6 to 5.5

http://civicrm.stackexchange.com/questions/9917/free-mandrill-usage-going-away-what-alternatives-work-well

I've just done that and the mailing is running now.

And, BTW, the errors were of type "Syntax Error".

I'd still really like to see this fixed. Will try and edit the issue title.

**Comment by joseltorres** [comment]
Unfortunately this is not something we can fix within this extension and is related to core civicrm. This issue will also impact users of any other smtp service that use SMTP over SSL/TLS. http://civicrm.stackexchange.com/questions/10964/smtp-connection-failing-problem?answertab=votes

**Comment by tabletguy** [comment]
Thanks. Was pretty sure this needed to be fixed in CiviCRM core, but not 100% sure. Also, the ticket leaves a good documentation trail. And your link helped too.
