### ISSUE TITLE
CiviMail records emails as bounced although they are valid emails and are sent through

### ISSUE THREAD

**Issue by madurak** [proexchange/com.pesc.sparkpost#24]
Hi,
I have run a stress test with around 30K emails and found that CiviMail reports that around 12K emails are bounced, but they are infact valid emails and are received in the email inbox.
Sparkpost records only around 6 emails as bounced and these are the only Invalid ones.
So i think CiviMail is doing something incorrect here, can you please take a look. Let me know if anymore info in required. Thanks.

CiviMail Report
![screen shot 2016-10-12 at 10 03 26](https://cloud.githubusercontent.com/assets/10810117/19306622/736da3da-906e-11e6-912b-02932dc5f101.png)

Sparkpost Bounces
![screen shot 2016-10-12 at 11 24 18](https://cloud.githubusercontent.com/assets/10810117/19306635/7b75c9ea-906e-11e6-8936-e7c7e9bf4b2f.png)

Also the bounce type says 'Syntax' instead of saying something like 'Invalid'?
![screen shot 2016-10-12 at 10 04 18](https://cloud.githubusercontent.com/assets/10810117/19306631/78cdfc94-906e-11e6-867d-0539c560da8d.png)

Test Environment:
CiviCRM: 4.6.21
Sparkpost: V 1.3.4

**Comment by joseltorres** [comment]
My guess is that civicrm is considering "delays" as bounces. We had that as default in an older version of the extension but removed it, but you can override thay with the params in the sparkpost fetch bounces scheduled job. Make sure the params only have the api key, everything else can be removed.

**Comment by joseltorres** [comment]
https://github.com/proexchange/com.pesc.sparkpost/issues/18

https://github.com/proexchange/com.pesc.sparkpost/commit/73cf9318b04941b9d6287bfa435a713d86edd971

Hope this helps... if not, let me know and I will dig deeper.

**Comment by joseltorres** [comment]
issue gone stale. closing, please reopen if you have an update.
