### ISSUE TITLE
Send limitations

### ISSUE THREAD

**Issue by mediasunrise** [proexchange/com.pesc.sparkpost#25]
We are only get 400 sends each time the cron job is run. Is that a limitation or setting in your plugin?

**Comment by joseltorres** [comment]
No... 

- your php might be timing out
- your civicrm might be throttled, see /civicrm/admin/mail?reset=1
- or sparkpost might be throttling, https://support.sparkpost.com/customer/portal/articles/2030894-daily-and-monthly-quota-limits
