### ISSUE TITLE
Issues with PHP 5.6

### ISSUE THREAD

**Issue by herbdool** [proexchange/com.pesc.sparkpost#26]
I'm wondering if anyone else is having issues with PHP 5.6. I'm trying to determine where it's failing. I'm sure it has something to do with https://civicrm.stackexchange.com/questions/16628/outgoing-mail-settings-civismtp-php-5-6-x-problem since this extension is working under PHP 5.5.

Somewhere in the chain it's failing and just wondering if there's something in the extension.

**Comment by joseltorres** [comment]
yeah... php 5.6, i think there are a few things you can do... some of them are in the stackexchange question you linked. See previous https://github.com/proexchange/com.pesc.sparkpost/issues/22

**Comment by herbdool** [comment]
Ah sorry for not reviewing the closed issues.

Just one additional question: the other issue mentions https://civicrm.stackexchange.com/questions/10964/smtp-connection-failing-problem?answertab=votes

In this thread someone makes the claim they've got it working with Sparkpost:

> Plus a zillion for not disabling peer verification! To speak directly to an example comment above our cert, ports, etc are set up properly and we have never had an issue connecting with Sparkpost using php 5.6.3

Interesting, but they don't say how they're connecting with Sparkpost, whether this extension, the other one or directly.

Someone also suggested putting ssl:// in front of the settings in Civi but that just gave errors.

**Comment by joseltorres** [comment]
this extension does almost nothing with SENDING, it adds a few smtp headers to track down bounces later on when the scheduled job runs. Sending with this sparkpost extension is handeled with CiviCRM builtin in SMTP client. If you having problems try using port 587 or 2525 (see: https://www.sparkpost.com/docs/faq/smtp-connection-problems). 

The other extension sends with using API calls built into the extension overwriting the CiviCRM SMTP client.

Hope this helps.

**Comment by herbdool** [comment]
Thanks for the clarification.

Yeah, I tried adding ssl:// with both port 587 and 2525 and it didn't like the settings with either.
