### ISSUE TITLE
Bounce processing doesn't work if VERP separator not "."

### ISSUE THREAD

**Issue by norristh** [proexchange/com.pesc.sparkpost#29]
For no good reason, I had changed the CiviCRM Administer->CiviMail->Mailer Settings->VERP Separator to be "+" instead of the default "."

This breaks the bounce processing in this extension.  In sparkpost.php, starting at line 177 where $params['Return-Path'] is exploded by ".", things break because the hash can't be created properly.  I believe that leads to the MailingEventQueue get failing, and other metadata not being set.

I tried changing line 177 to explode with "+" instead of "." but that didn't help.  So I just changed my VERP Separator back to "." and things work fine.

I don't know that you need to make it support different VERP Separators, but maybe the documentation should warn about this somewhere.

**Comment by joseltorres** [comment]
@norristh Thanks for letting us now. We'll make sure to have a fix for this in our next release.

**Comment by mark-rodgers** [comment]
Should be fixed now. Try release 1.3.5
