### ISSUE TITLE
Civi CRM Sparkpost - pesc.sparkpost - Error Sending Group Subscription Welcome Emails

### ISSUE THREAD

**Issue by omniscitoad** [proexchange/com.pesc.sparkpost#30]
So, I'm using the com.pesc.sparkpost CiviCRM/Sparkpost integration extension. It is working really well so far for just about everything except for the welcome email for mailing list group subscriptions. I've tried through a drupal webform and through a Civi profile (using checkmark boxes for public subscriber groups). In both cases, the double-opt-in email gets sent properly, and the link in the double-opt-in email works properly. Upon clicking the link I am sent to a confirmation page with an error message (bellow), but the welcome email is never sent, and the transactional email is shown as pending on the user's profile in Civi.

So, Transactional emails and Mass mail are definitely being sent fine through Sparkpost, and the subscription mechanism is working as intended. So I'm pretty sure that my sparkpost smtp settings are working as intended, contrary to the error message. So far it seems to be just these welcome emails that aren't sending properly.

Civi CRM 4.6.30
com.pesc.sparkpost 1.3.4

> An error occurred when CiviCRM attempted to send an email (via SMTP). If you received this error after submitting on online contribution or event registration - the transaction was completed, but we were unable to send the email receipt.
> 
> The mail library returned the following error message: Failed to send data [SMTP: Invalid response code received from SMTP server while sending email. This is often caused by a misconfiguration in Outbound Email settings. Please verify the settings at Administer CiviCRM >> Global Settings >> Outbound Email (SMTP). (code: 550, response: 5.7.1 Unconfigured Sending Domain )]
> 
> This is probably related to a problem in your Outbound Email Settings (Administer CiviCRM » System Settings » Outbound Email), OR the FROM email address specifically configured for your contribution page or event. Possible causes are:
> 
> Your SMTP Username or Password are incorrect.
> Your SMTP Server (machine) name is incorrect.
> You need to use a Port other than the default port 25 in your environment.
> Your SMTP server is just not responding right now (it is down for some reason).
> The FROM Email Address configured for this feature may not be a valid sender based on your email service provider rules.

>(i) Name (email@example.com) has been successfully subscribed to the mailing list.

**Comment by joseltorres** [comment]
webform will send an email from the site email address defined in drupal. That domain also needs to be added as a sending domain in sparkpost. Also I like using one of these two modules for drupal

and if you're sending from the contact record
![image](https://user-images.githubusercontent.com/11579459/42119317-55353dea-7bbf-11e8-94fd-3d8f65d63e94.png)

then the from address, which defaults to the logged in user, also needs to be in sparkpost's sending domains

![image](https://user-images.githubusercontent.com/11579459/42119364-ac13fb7e-7bbf-11e8-8135-f3e935f270b0.png)



- https://www.drupal.org/project/smtp
- https://www.drupal.org/project/sparkpost
