### ISSUE TITLE
CiviEvent not sending confirmation emails

### ISSUE THREAD

**Issue by davyrhys** [proexchange/com.pesc.sparkpost#32]
I've installed the extension on a D6 setup with Civi5.1.0.
The instal and testing went fine and the test email via smtp sends.
But event confirmation emails are not sent, and the event process errors out with 

> "Sorry, due to an error, we are unable to fulfill your request at the moment. You may want to contact your administrator or service provider with more details about what action you were performing when this occurred.  source_contact_id is not a valid integer"

There is a Stackexchange report on the error which suggests 

> "_it seems that there is a bug in the main sparkpost.php file which has source_record_id instead of source_contact_id. So I think the error was caused because source_contact_id was being left undefined."_

(https://civicrm.stackexchange.com/questions/24657/event-registration-fatal-error-since-v5-0-1) 

Can you help? 
Thanks, Davy

**Comment by davyrhys** [comment]
I appear to have fixed the problem. I edited sparkpost.php and replaced _source_record_id_ with _source_contact_id_

**Comment by joseltorres** [comment]
thanks for pointing this out. We'll look at and fix.

**Comment by davyrhys** [comment]
Thanks Jose. And thanks for the great extension.

**Comment by davyrhys** [comment]
Quick update FYI

The problem I experienced was on a D6 setup with CiviCRM 5.0.0.

I've just installed a clean unedited version of the extension on a D7.59 setup with CiviCRM 5.1.0 and it worked flawlessly without any need to edit sparkpost.php
