### ISSUE TITLE
make 'friendly_froms' optional parameter in api

### ISSUE THREAD

**Issue by joseltorres** [proexchange/com.pesc.sparkpost#5]
in most cases the sparkpost account will be used with only one civi account, in that situation filtering with friendly_froms will not be required

**Comment by mark-rodgers** [comment]
friendly_froms has been made optional in release v1.0.

https://github.com/proexchange/com.pesc.sparkpost/commit/5527c56220205ced658e56bfc14c5757bdf323d7
