### ISSUE TITLE
Bounce doesn't seem to be reflected in CiviCRM

### ISSUE THREAD

**Issue by laryn** [proexchange/com.pesc.sparkpost#6]
I set up a contact with a nonexistent email address and did a "Send an email" action. The message shows as a bounce in SparkPost, but I see no evidence that the bounce was reflected in CiviCRM after the Scheduled Job is run.

Here's the events line of my Scheduled Job, underneath the `api_key` and `friendly_froms`:

> `events=bounce,delay,policy_rejection,out_of_band,spam_complaint`

Am I missing a step?

**Comment by joseltorres** [comment]
It only works for the bulk emails (civimail). CiviCRM only includes b.###.###.[hash]@exmaple.org return-path header during bulk mailings. We basically insert that return-path header into tags that we can then query from sparkpost with their API. Try adding the contact to a group for mailing and send out bulk mailing. We may work in these type of emails later, but right now we're focused on bulk emails.

**Comment by laryn** [comment]
Hmm... still doesn't seem to be working even from CiviMail. I will try to test further later.
I guess this is a different method than the Mandrill extension, which uses a webhook on bounce events to notify CiviCRM. (I see SparkPost does allow webhooks, so perhaps that could be used in the future)

**Comment by joseltorres** [comment]
did you make sure to fill in the correct parameters for the scheduled job, enable it, and execute it?

**Comment by laryn** [comment]
Yes, I have info in the `api_key`, `friendly_froms` and the `events` parameter as above. I submitted the mailing, manually ran the Mailings job, then waited until I saw the bounce in SparkPost and manually executed the SparkPost scheduled job.

**Comment by joseltorres** [comment]
What does the job log say for the scheduled job? you can email me at jtorres [at] pesc [dot] com... I'd like to see know what is going on to try and fix an issue if it exist.

a few other things to check: in the sparkpost api do you see something like this in the bounce event?
 "rcpt_meta": {
        "civi-rp": "b.557.3204.7e8e795fc2298176@example.org"
      },

also, you need to be on civi 4.6+

**Comment by laryn** [comment]
This is on 4.6. Here's the summary and I'll email you with more detail.

`Entity: SparkPost Action: Fetchbounces
Summary
Finished execution of SparkPost Fetch Bounces with result: Success (a:0:{})`

**Comment by laryn** [comment]
The issue was that the `friendly_froms` parameter didn't match the from address of the mailing exactly.

**Comment by joseltorres** [comment]
`friendly_froms`
is a **case-sensitive**, comma-separated list (ex: info@example.com,marketing@example.com,director@example.com)
