### ISSUE TITLE
Why is friendly forms case sensitive?

### ISSUE THREAD

**Issue by tabletguy** [proexchange/com.pesc.sparkpost#9]
Email addresses are not case sensitive in email clients. I can understand how the default equality check on a linux machine would be case sensitive, but why doesn't the code either do a case insensitive check, or, perhaps, if needed to send through the API, why not always force to lowercase when sending to sparkpost, and then doing a case insensitive compare when it returns?

**Comment by joseltorres** [comment]
While I personally agree that all email addresses should be lower-case, there might be some people that want might want to emphasize certain letters in their sending addresses (ex: SUPERme@eXamle.org). 

I actually just updated extension, the scheduled job no longer uses the friendly_froms parameter. That value is now handled behind the scenes, using the email addresses specified in the settings Administer > CiviMail > From Email Addresses.

**Comment by joseltorres** [comment]
**\* also, we didn't compare the friendly_froms anywhere, it's how the sparkpost API handles that parameter. I think it's odd they care if the email came from jose@example.com or Jose@example.com, but that's how it works with them. But if you use the newest version you don't need to worry about it. The extension will use whatever case you have in the email addresses specified in the settings Administer > CiviMail > From Email Addresses
